### ISSUE TITLE
Trailing/leading whitespace in emphasis/strong spans isn't serialized correctly

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror-markdown#1]
I.e. you'll end up with Markdown like `foo * bar*` which the Markdown parser won't actually recognize as emphasis because there's whitespace after the asterisk.

Originally reported [here](https://github.com/ProseMirror/prosemirror/issues/19)

**Comment by TimothyGu** [comment]
In this situation, rather than outputting invalid Markdown, it might be better to move the whitespace in the emph/strong span out of the span (i.e. <code>foo&nbsp;&nbsp;\*bar\*</code>)

**Comment by owjsub** [comment]
This issue commonly affects iOS/Android users. They are more likely to add a space before toggling emphasis.
