### ISSUE TITLE
in parser, allow spec to to read child info

### ISSUE THREAD

**Issue by mhuebert** [ProseMirror/prosemirror-markdown#10]
A tag like `<table>` has an attribute, `columns`, which can only be known after child nodes have been parsed. 

The following patch supports a `handleClose` function in a parser spec which could be used to add or update `attrs` to the node when its `close` tag has been reached. I'm posting here for feedback before submitting as a PR; this works for me but I'm not sure if there would be a better/preferred approach. 

Patch:
https://github.com/mhuebert/prosemirror-markdown/tree/patch-1

Example usage:
```js

{ // ...in token map...
  table: 
  { block: "table",
    handleClose: function (node) {
      // copy attrs from first child, which will be `thead`
      node.attrs = node.content[0].attrs
    }
  },
  thead: 
  { block: "table_header",
    handleClose: function (node) {
      // copy attrs from first child, which will be `tr`
      node.attrs = node.content[0].attrs
    }
  },
  tr: 
  { block: "table_row",
    handleClose: function (node) {
      // column count is equal to number of child nodes
      node.attrs = {columns: node.content.length}
    }
  }
 // ...
}
```
In the case of a table, we want the `column` attribute to 'bubble up' from `tr` elements, up to `thead` or `tbody` elements, and then finally the `table` itself. Copying the attr to the intermediate parents seems necessary so that we can enforce content constraints, eg. for a table body, `"table_row[columns=.columns]+"`.

(Note that to support Github-style markdown tables, a different schema is required than what [prosemirror-schema-table](https://github.com/ProseMirror/prosemirror-schema-table) specifies, as table headers are _required_ - it's not possible to have a table without `<thead>` and `<th>` elements.)

**Comment by marijnh** [comment]
The approach to tables that uses a width attribute is likely to be deprecated in the future, in favor of using a plugin with an appendTransaction function to ensure rectangular shape instead of schema-level restrictions (which makes things like colspan and rowspan possible), and such an approach wouldn't have this problem. Maybe you can build your tables like that?

**Comment by mhuebert** [comment]
Hmm. Markdown tables don't support colspan, so maybe it makes sense to enforce it at the schema level, but I haven't written any plugins yet so I will have to learn more about transactions to know how that would work. Do you know offhand any plugins that have a similar appendTransaction function that would be worth look at?

**Comment by marijnh** [comment]
The new-style table implementation hasn't been open-sourced yet, but in effect, what it does is scan the document for tables, and for those that aren't rectangular, append a transaction that inserts cells to make them rectangular.

**Comment by mhuebert** [comment]
OK. Does that mean on every transaction it is scanning the whole doc to find and validate all the tables? (or is there a way to only scan things that were edited in the last transaction?)

**Comment by marijnh** [comment]
You can write a helper (but it's not part of the library yet) that recursively descends two documents (the one before the transaction and the one after) and skips nodes that are the same in both, in order to make scanning huge document for this kind of consistency issues cheap.

**Comment by mhuebert** [comment]
OK, that makes sense. 

I do like the behavior that comes with schema constraints; when deleting the contents of a cell, the cell remains in place, and the cursor jumps to the previous cell. Without schema constraints, the cell itself is deleted, meaning the neighbouring cell gets shifted to a different column. Example: https://www.youtube.com/watch?v=JBVVCt_C7tw

**Comment by marijnh** [comment]
Deleting the whole cell when you delete its contents shouldn't happen. How exactly are you deleting it?

I agree that the schema-constraint formulation of table shape is attractive, but it's a pain to parse cleanly (as you found), doesn't generalize well at all, and basically feels like a hack, so I'm not happy with it.

**Comment by mhuebert** [comment]
I was deleting the cell contents via backspace. However, I just realized the :isolating key was only added in 0.21.0, and I hadn't seen the update - now the behavior is great.

Even without a plugin / appendTransaction function, I think this should be ok for now - I don't see any obvious ways that a user will end up with an imbalanced table.

Table row-count was only issue so far where I needed lower-level access in the parser so I'll close this now.
