### ISSUE TITLE
Allow list items to start with other nodes than paragraphs

### ISSUE THREAD

**Issue by max-nextcloud** [ProseMirror/prosemirror-markdown#100]
According to the schema all list items have to start with a paragraph.

However this is not the case in the common mark spec:
https://spec.commonmark.org/0.30/#example-300

This is valid markdown:

```markdown
- ## Foo
  some detais about foo
- ## Bar
```
and results in:

- ## Foo
  some detais about foo
- ## Bar

However pasting this into the prosemirror markdown example results in:

![grafik](https://github.com/ProseMirror/prosemirror-markdown/assets/97337118/e4914818-a046-43ea-9e3b-019e5f53f4fa)

**Comment by max-nextcloud** [comment]
I know I can use my own schema and in fact we do. Is there any reason enforcing paragraphs at the start of a list item?

**Comment by marijnh** [comment]
No, I'm not sure why that was this way. Attached patch changes it.
