### ISSUE TITLE
expelEnclosingWhitespace not working with inner links

### ISSUE THREAD

**Issue by ndoherty-xyz** [ProseMirror/prosemirror-markdown#107]
## Bug
The `expelEnclosingWhitespace` option is not applied to marks with inner links 

## Example & Reproduction:
Can easily be replicated on https://prosemirror.net/examples/markdown/ by creating text with the cases below:
- italicized text with an inner link and whitespace at the end
- bolded text with an inner link and whitespace at the end
- italicized text with an inner link and whitespace at the front

![Kapture 2023-08-02 at 12 29 01](https://github.com/ProseMirror/prosemirror-markdown/assets/103902448/aa57b113-e836-447c-a948-0018713f2e76)

## Issue in the code
- Did some digging within the package, and this seems to be related to the changes in [this commit](https://github.com/ProseMirror/prosemirror-markdown/commit/1d644b7d15805faa8d9954046592807154819b7a) 
  - Specifically because of the added check in the `if` statement

Happy to help fix this, but I'm new to the internals of Prosemirror and and missing some context around what this added check is accomplishing.

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch should help.
