### ISSUE TITLE
Mark's aren't serialized if root node isn't a block container

### ISSUE THREAD

**Issue by spaceemotion** [ProseMirror/prosemirror-markdown#109]
I have created the following snippet to convert the user's selection into markdown:

```ts
export const getMarkdownSelection = (state: EditorState, options?: SerializeOptions) => {
  const slice = state.doc.slice(state.selection.from, state.selection.to);

  // 1. Create a temporary state for the selection
  const tempParagraph = state.schema.nodes.paragraph.create({}, slice.content);
  const tempDoc = state.schema.nodes.doc.create({}, tempParagraph);

  // 2. Serialize the temporary Node
  return serializer.serialize(tempDoc, options);
};
```

If I remove the extra paragraph wrapping, it no longer serializes the text properly, as the root render method only renders the child nodes, without checking the root/parent node.

https://github.com/ProseMirror/prosemirror-markdown/blob/b7c1fd2fb74c7564bfe5428c7c8141ded7ebdd9f/src/to_markdown.ts#L262-L266

By wrapping it in a paragraph, this will now call the `renderInline` method required for serializing the marks.

Is this a bug or an intentional internal consideration?
AFAIK slice fragments rarely contain the full document structure.

**Comment by marijnh** [comment]
> If I remove the extra paragraph wrapping, it no longer serializes the text properly, as the root render method only renders the child nodes, without checking the root/parent node.

The docs for `serialize` say "Serialize the content of the given node", so this looks like it is intentional.

**Comment by spaceemotion** [comment]
Thanks for the clarification!
