### ISSUE TITLE
Markdown-It is not ESM

### ISSUE THREAD

**Issue by wagenet** [ProseMirror/prosemirror-markdown#110]
Markdown-It ships as CJS which causes problems for ESM builds.

```
[!] RollupError: "default" is not exported by "../../node_modules/.pnpm/markdown-it@13.0.1/node_modules/markdown-it/index.js", imported by "../../node_modules/.pnpm/prosemirror-markdown@…
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
../../node_modules/.pnpm/prosemirror-markdown@1.11.2/node_modules/prosemirror-markdown/dist/index.js (2:7)
1: import { Schema, Mark } from 'prosemirror-model';
2: import MarkdownIt from 'markdown-it';
```

**Comment by Nness** [comment]
Markdown-IT seems lack on maintenance, @marijnh has commented on [maintenance status of markdown-it](https://github.com/markdown-it/markdown-it/issues/948#issuecomment-1729246196). Of course to wish someone pick up markdown-it project is one way to get around.

Alternatively, I notice [remarkjs](https://github.com/remarkjs/remark), it will compile markdown into abstract syntax tree. And it has been actively maintained, also all remarkjs official plugins are ESM only. It should be possible to convert prosemirror-markdown to use remarkjs?

**Comment by marijnh** [comment]
There is [work](https://github.com/markdown-it/markdown-it/pull/863) happening to push markdown-it into the 2020s, but it's slow going. Switching to another parser would be a breaking change, so it's not really attractive either. It might end up being the only way forward, but I'm not quite ready to give up on markdown-it yet.

**Comment by Violeta-Amza** [comment]
there is a new version released for markdown-it , check: https://github.com/markdown-it/markdown-it/issues/948#issuecomment-1846473211 

@marijnh can you update the used version?
