### ISSUE TITLE
Numbers in headers

### ISSUE THREAD

**Issue by possan** [ProseMirror/prosemirror-markdown#112]
I stumbled upon something that i'm not sure if it's a bug or a feature in the serializer...

If i create a heading in the editor and add a text fragment with what looks like an ordered list inside it `1. hello`, it will be escaped as `# 1\. hello` when serialized, and i'm not sure if this is correct or not, i couldn't find anything on the commonmark page about it either.

Also noticed that there had been some work done on escaping and lists in master recently.

I have a test and a fix in a fork but it feels like a very hacky way of fixing it...

https://github.com/ProseMirror/prosemirror-markdown/compare/master...possan:prosemirror-markdown:possan/numbers-in-headers?expand=1

**Comment by marijnh** [comment]
Attached patch should help.
