### ISSUE TITLE
Don' escape `+++` at the start of a line when serializing

### ISSUE THREAD

**Issue by remorses** [ProseMirror/prosemirror-markdown#113]
Some markdown renderers use these sequences for custom elements, for example [retype tabs](https://retype.com/guides/formatting/#tab)

Multiple `+` should be safe in commonmark

I can open a PR if you agree

**Comment by marijnh** [comment]
Sure, a PR that makes the escaping of `+` list markers happen only when they are followed by a space would work for me.
