### ISSUE TITLE
Markdown parser combines two or more same autolink into a single anchor element

### ISSUE THREAD

**Issue by vivinkrishna-ni** [ProseMirror/prosemirror-markdown#115]
## Issue

When two or more [autolink ](https://spec.commonmark.org/0.30/#autolinks) markdowns are given as an input to the markdown parser without a space in between the autolinks render as a single anchor element.

## Repro

Markdown string `<link:1><link:1>` given to the `parser()` method of markdown parser. Please note that the links within the `<>` are the same and no whitespace between them.

Reproducing the same in prosemirror markdown editor in the example given in https://prosemirror.net/examples/markdown/
![prosemirror-same-link-issue](https://github.com/ProseMirror/prosemirror-markdown/assets/123377523/2eded38b-3533-4885-8e46-0aab74d06212)

## Current behavior

They are parsed as a single anchor element combined as below
```HTML
<a href="link:1">link:1link:1</a>
```

However, if we give two different links without a space or the same link with a space, they are parsed as expected. 

## Expected behavior

They should be parsed as two separate links
```HTML
<a href="link:1">link:1</a>
<a href="link:1">link:1</a>
```

## Context 

We use markdown parser and serializer to store the information for our rich text editor and we extend the prosemirror-markdown to leverage our needs. However, we enable only `autolink` feature from CommonMark flavor as part of our requirement.

**Comment by marijnh** [comment]
The way ProseMirror marks work, there is no concept of individual links, just text styled with link marks. So this distinction cannot be represented in ProseMirror's document model, and what you are looking for here will not be supported by prosemirror-markdown.

**Comment by vivinkrishna-ni** [comment]
Thanks @marijnh for your quick response. Since we use both parser and serializer for converting markdown to DOM and vice versa, the serializer changes the data that is given to the editor. For example, with the same markdown string `<link:1><link:1>`, serializer would return `[link1link1](link1)` as the parser changes the DOM. This alteration in the original user-input markdown string can result in data loss or modification.

Also, when we tried with the common mark example editor or in markdown-it demo editor, we observed that they converted the same input into two different anchor elements. 
![image](https://github.com/ProseMirror/prosemirror-markdown/assets/123377523/c1a8f330-6eb3-4ef9-8606-5a70f2aad791)

So, it would be really helpful if there is any configuration we can utilize either in the parser or in the serializer to preserve the original markdown string that has been given earlier.

**Comment by marijnh** [comment]
The markdown serialization/parsing is never going to be lossless (there's things that ProseMirror can express that Markdown cannot, such as spaces at the start of an emphasized span, and vice versa, such as this). That's just not something this package attempts to provide.
