### ISSUE TITLE
How to use with Tables?

### ISSUE THREAD

**Issue by god-of-javascript** [ProseMirror/prosemirror-markdown#116]
Is there any explanation or example of how to use this library with
https://github.com/ProseMirror/prosemirror-tables

Should we clone this repo and use https://www.npmjs.com/package/markdown-it-table to do so?

**Comment by marijnh** [comment]
No, there isn't. I don't think it'd be easy to combine the two, since Markdown tables don't store things like column width.

In any case, this is a bug tracker, not the place for questions, so I'm closing this.
