### ISSUE TITLE
symbol | in table cells

### ISSUE THREAD

**Issue by ElenaMikhaylova** [ProseMirror/prosemirror-markdown#118]
Issue
I use markdown serializer and when symbol | is presented inside table cell node, it breaks table structure. 

Repro
For example I need to serialize this table:
<img width="616" alt="Снимок экрана 2024-03-13 в 10 11 36" src="https://github.com/ProseMirror/prosemirror-markdown/assets/36405284/ac260447-ec3c-4342-a1f9-65cfe8432a02">

Current behavior
It breaks like this:
<img width="622" alt="Снимок экрана 2024-03-13 в 10 11 54" src="https://github.com/ProseMirror/prosemirror-markdown/assets/36405284/456b1bfc-df55-4e53-b3ef-2baba06b2a08">

Result markdown:
```
 | table header 1 | table header 2 | 
 | --- |--- |
 | table cell 1 | 0 | table cell 2 | 
```

Expected behavior
Symbol | inside text node in table cell should not recognized as column separator

**Comment by marijnh** [comment]
This package doesn't even define a parser/serializer for tables, so I'm going to close this issue.
