### ISSUE TITLE
update `MarkdownSerialize.serialize` type to accept `Fragment`

### ISSUE THREAD

**Issue by BrianHung** [ProseMirror/prosemirror-markdown#120]
It looks like `MarkdownSerialize.serialize` can be used to serialize `Fragment` because `Fragment` and `Node` share the same `forEach` API. Is it possible to update the type to be `Node | Fragment`?

Finding it useful right now to serialize a `Fragment` that comes from selection

```js
const slice = state.selection.content();
defaultMarkdownSerializer.serialize(slice.content)) // Argument of type 'Fragment' is not assignable to parameter of type 'Node'.
```

**Comment by marijnh** [comment]
This would conflict with the type of the `nodes` functions, which take a parent node, not a parent fragment, so this cannot really be done in a backward-compatible way.

**Comment by BrianHung** [comment]
Ah I see your point; none of my `toMarkdown` functions use the third param `parent` so I didn't run into this type conflict. Is there an example code of how you would take a Fragment and create a valid Node from that?

**Comment by marijnh** [comment]
You should be fine to pass in an invalid node (by just calling `NodeType.create`) here, since the node is never checked or modified.

**Comment by BrianHung** [comment]
Good callout; I also saw someone was attempting the same thing here: https://github.com/ProseMirror/prosemirror-markdown/issues/109#issue-1857802372 😅
