### ISSUE TITLE
Markdown-it import path does not align with current package

### ISSUE THREAD

**Issue by rajsite** [ProseMirror/prosemirror-markdown#124]
The following Token import does not align with what is exported from markdown-it:
https://github.com/ProseMirror/prosemirror-markdown/blob/e59521463f62b296cc072962aa2d60b267ea4397/src/from_markdown.ts#L3

This is not detected by TypeScript because the package is currently using [v13 types](https://github.com/ProseMirror/prosemirror-markdown/blob/e59521463f62b296cc072962aa2d60b267ea4397/package.json#L32) with the [v14 package](https://github.com/ProseMirror/prosemirror-markdown/blob/e59521463f62b296cc072962aa2d60b267ea4397/package.json#L27).

The v14 package switched to esm exports, but [did not define bare module paths](https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/package.json#L21-L23). So if you clone this repo, update to the v14 types and look in vscode you get errors about the bare module import of Token not existing:

![image](https://github.com/user-attachments/assets/eb29caff-c8d3-4ecd-aab4-9cf7e30f047b)

This caused an issue for us upstream as we tweak some MarkdownParser behavior so imported the v13 types and with an attempted upgrade of our types to v14 our TypeScript build was failing.

Because this is a type only import it seems to be safe to update the types to v14 and update the import to:

```ts
import type Token from "markdown-it/lib/token.mjs";
```

Which is elided from the cjs/js builds (the different cjs/mjs exports never include the type import) and it fixes the TypeScript issues.

**Comment by marijnh** [comment]
Thanks for spotting that. Attached patch upgrades the dependency. `import type` doesn't seem to be needed—TypeScript will automatically drop type-only imports from its build output.
