### ISSUE TITLE
Code blocks after a list parsed as continuation of the list item 

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror-markdown#17]
Originally submitted by @amkgo as https://github.com/ProseMirror/prosemirror/issues/732

In the markdown example, the first line of the code block after list will change to a list when add a paragraph after list. See screen cast below.

![prosemirror](https://user-images.githubusercontent.com/8333491/33446028-a123948e-d5b3-11e7-96a8-91a83c4b63aa.gif)

Andrew

**Comment by marijnh** [comment]
The problem appears to be that this is parsed not as code, but as a continuation of the list item. It seems Markdown is really poorly suited for structured data representation, because of all these edge cases.

It might be worthwhile to detect these (there being an indentation context before a code block) and output triple-backtick code blocks instead. Or maybe we should just always output triple-backtick code blocks.

**Comment by amkgo** [comment]
I've ask similar question at [CommonMark Reference Implementation](https://github.com/commonmark/CommonMark/issues/510). 

From the answer I think we can do it as following:
1. When select `code` style: Use `<pre><code>`  wrap all the selected paragraphs
2. When convert HTML to Markdown: convert the `<pre><code>` block to fenced block
3. When convert Markdown to HTML: convert fenced block to `<pre><code>` block

That should works.
