### ISSUE TITLE
Markdown-It dependency

### ISSUE THREAD

**Issue by Charius** [ProseMirror/prosemirror-markdown#19]
Hello! I've got a couple of questions.

Is there any reason to have ^6.0.4 instead of latest version of markdown-it?

And if there is no reasons why not update the dependency?

**Comment by marijnh** [comment]
No reason. If you want to run the tests with the current version and submit a pull request that upgrades, that'd be fine.

**Comment by Charius** [comment]
@marijnh thanks for the answer! I'll try to do it when will have some time!

**Comment by marijnh** [comment]
Merged #27
