### ISSUE TITLE
Schema definition has duplicate entries

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror-markdown#2]
There are duplicate entries for `ordered_list`, `bullet_list` and `list_item`. 

I also noticed that `code_block` serializing / deserializing deals with data attributes.

**Comment by marijnh** [comment]
Fixed in attached patch. Yes, `code_block` uses a data attribute to store the parameters of the block. Is that problematic?

**Comment by rsaccon** [comment]
Not problematic for me.
