### ISSUE TITLE
Wrongly escaped $ at the start of a line

### ISSUE THREAD

**Issue by Danita** [ProseMirror/prosemirror-markdown#22]
We were investigating why a single line like

```
$50
```

was being serialized into the following markdown:

```
\$50
```

We discovered in `to_markdown.js` there's an `esc()` method which uses a regex to escape certain characters that could have special meaning at the start of a line, but the offending regex `/^[:#-*+]/` contains a range `#-*` which provokes that `$%&'()` also be matched, which we assume wasn't your intention.

A simple fix would be move the `-` to the end or start or end of the character class, such as `/^[-:#*+]/`.

[This commit](https://github.com/ProseMirror/prosemirror-markdown/commit/b6552842c298372ac8087ab398ce1e24ad734ec6) appears to be where the bug was introduced.

**Comment by marijnh** [comment]
You're entirely right—that `-` should have been escaped. I've done so in attached patch and released 1.1.1 with the fix.
