### ISSUE TITLE
Prosemirror Markdown example does weird things with code blocks

### ISSUE THREAD

**Issue by Hacktivista** [ProseMirror/prosemirror-markdown#26]
A video will show it better than words...

![markdown_code](https://user-images.githubusercontent.com/5282749/44450626-d4ad4400-a5c7-11e8-89e4-8d6a9d201fc5.gif)

As you can see in the GIF, switching between code and no-code is very tricky. I kind-of understand why it happens (all has to do with the paragraphs in markdown), but actually is pretty confusing.

Problems are:
- If I have no text after a code block, I can't leave it without losing format in all lines.
- After returning to a paragraph block the different lines in the previous code block are shown separate, if I write anything else, the contiguous lines are put together in a single line.
- If I select various paragraphs, and set them to code block, it creates one code block per paragraph.

Solutions might be:
- If I press backspace in an empty codeblock line, transform the current line into a paragraph.
- If I transform a codeblock into a paragraph, put contiguous lines together immediately. If I do select a single line, transform that line into a paragraph and leave the rest as a codeblock.
- If I select various paragraphs, and transform them into a codeblock, create a single codeblock with them.

**Comment by Hacktivista** [comment]
I thought the 2nd and 3rd problem were related to Markdown, sorry, didn't notice it happened everywhere. Thanks you :)

**Comment by marijnh** [comment]
I've opened https://github.com/ProseMirror/prosemirror/issues/841 to track the weird newline behavior
