### ISSUE TITLE
Serialization of code blocks introduce 'null' or 'undefined' textual content

### ISSUE THREAD

**Issue by thomasWajs** [ProseMirror/prosemirror-markdown#31]
### Repro

http://prosemirror.net/demo/markdown.html

Copy/Paste content wrapped in a code blocks into the WYSIWYG  editor.

Switch between WYSIWYG and Markdown mode.

### Result

![prosemirror markdown](https://user-images.githubusercontent.com/1587402/48848034-4b163980-eda3-11e8-9ba7-1b3592c26426.gif)

My HTML test content :

`<pre><code>Text wrapped in code</code></pre>`

### Origin

https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/to_markdown.js#L55

`state.write("```" + node.attrs.params + "\n");`

node.attrs.params may be null or undefined.

**Comment by marijnh** [comment]
Should be better with attached patch.

**Comment by thomasWajs** [comment]
Absolutely, thanks ! :+1:
