### ISSUE TITLE
Serialize autolinks as <url> rather than [url](url)

### ISSUE THREAD

**Issue by DouweM** [ProseMirror/prosemirror-markdown#32]
- Original Markdown: `<https://github.com/ProseMirror/prosemirror-markdown>`
- Rendered HTML: `<a href="https://github.com/ProseMirror/prosemirror-markdown">https://github.com/ProseMirror/prosemirror-markdown</a>`
- Expected serialized Markdown: `<https://github.com/ProseMirror/prosemirror-markdown>`
- Actual serialized Markdown: `[https://github.com/ProseMirror/prosemirror-markdown](https://github.com/ProseMirror/prosemirror-markdown)`

I made an attempt at writing generic support for dynamic mark delimiters in [an early iteration](https://github.com/ProseMirror/prosemirror-markdown/compare/master...ad6cb453a44530dd07cec01bf3bee331efa2be46) of https://github.com/ProseMirror/prosemirror-markdown/pull/29, which would have made it relatively easy to fix this serialization as well, but that PR was ultimately replaced by https://github.com/ProseMirror/prosemirror-markdown/commit/0448d327d7b5c8cbfa95bd7283f12e4827df5218 which was specific to code marks but was much less complex.

**Comment by DouweM** [comment]
@marijnh Can you please share some thoughts on how you would implement this? 

In the PR mentioned above, [you suggested](https://github.com/ProseMirror/prosemirror-markdown/pull/29#discussion_r232983665) "giving the function that produces the delimiters access to the inline node(s) that the mark applies to."

If I'm understanding correctly, that would mean that when we come across a new mark, we immediately look ahead to find all the following nodes that mark applies to, so we can pass these to the `before` function, and we'd keep track of them somehow so we can also pass them to the `after` function later. The functions would then look at the text content of these nodes, and compare it to the mark's `src`, to determine how to render the link.

Assuming we don't want to make the implementation of this node-tracking too specific to links, how do you imagine us keeping track of these nodes across nested and overlapping marks?

**Comment by marijnh** [comment]
Hm, good question. I think the most reasonable way to support this without adding a lot of complexity or expensive node-enumerating for every mark is to pass the context fragment and index to the callbacks that create the open/close strings. I should have used that for backtick counting as well, I suppose, but unfortunately didn't, so now for backwards compat the interface got kind of clumsy, but that's survivable. Does attached patch look reasonable to you?

**Comment by marijnh** [comment]
Oh, hold on, I never released that backtick patch yet, so I can still break compatibility!

**Comment by marijnh** [comment]
That's better. Let me know if these work for you, and I'll release them.

**Comment by DouweM** [comment]
@marijnh Thanks! The behavior is exactly what I was looking for, so in that sense they certainly work for me.

I still somewhat prefer [my own approach](https://github.com/ProseMirror/prosemirror-markdown/compare/master...ad6cb453a44530dd07cec01bf3bee331efa2be46) at generic support for dynamic delimiters, because it's easier to write `before`/`after` functions that deal with text content, than with `parent` and `index`, and we don't end up with a `text` argument that's only provided in some cases (`escape: false`), but not all, but ultimately that doesn't matter so much because few people will be adding their own marks with dynamic behavior anyway. I also think the logic around `expelEnclosingWhitespace` is a lot easier to understand in my version than the current `master`, but that may just be me.

Either way, if you release a new version with the patches you've added, I can move forward with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/22797 and I'll be very happy!

**Comment by marijnh** [comment]
> we don't end up with a text argument that's only provided in some cases 

Since the latest patch, that's no longer the case.

I've released this as 1.3.0

**Comment by DouweM** [comment]
@marijnh Perfect, thank you!

**Comment by marijnh** [comment]
Hold on, I messed something up. Re-doing the release

**Comment by marijnh** [comment]
And done!
