### ISSUE TITLE
Code Block in MarkDown

### ISSUE THREAD

**Issue by prashant1k99** [ProseMirror/prosemirror-markdown#39]
The Code block ` ``` ` is created right after the last back-tick. As it should convert after the space is entered. Thus if the user wants they can use ` ```js ` for getting syntax highlighting.

**Comment by marijnh** [comment]
The inputrule that you refer to (which I assume is the one from prosemirror-example-setup) does not support languages on code blocks, so there's not much sense in saying that it 'should' work differently. Write you own, if you need a different approach.

**Comment by ncphillips** [comment]
Tinacms implements a rule like this. You press space at the end to create the block. It’s not ideal, but it works. 


https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/fields/src/Wysiwyg/state/plugins/input-rules/inputRules.ts#L171
