### ISSUE TITLE
Option to set tight list style on document level

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror-markdown#4]
Currently one can set a `tight` attribute on a list node to control how it gets serialized. I have a use case where my nodes do not have such an attribute, but I would like to serialize all list nodes of the document using the tight style.
I haven't seen a way to control this on the document level. One way to allow this, would be to support an optional `tightLists` serializer option, which would be used as the default style if no `tight` attribute is set on a list node.

**Comment by marijnh** [comment]
Sounds like a good idea. Want to submit a PR?

**Comment by kiejo** [comment]
Yes, I'll submit a PR later today or tomorrow!

**Comment by marijnh** [comment]
Done via #5
