### ISSUE TITLE
Issue with hard breaks in headline

### ISSUE THREAD

**Issue by buddh4** [ProseMirror/prosemirror-markdown#40]
When adding a hard break `Ctrl+Enter` within a headline the markdown result is:

```
## asdf\
asdf
```

Which will be rendered as:

![grafik](https://user-images.githubusercontent.com/9800854/81960140-c7907e00-9610-11ea-9a72-68c3367f0d49.png)

My workaround was to use the `splitBlock` command in the `Ctrl+Enter` keymap if the selection resides within a headline.

**Comment by marijnh** [comment]
This was a mismatch between that ProseMirror's schema allowed and what the Markdown parser accepted—ProseMirror allowed hard breaks in title nodes, but CommonMark apparently forbids that. I've adjusted the schema in attached patch.

**Comment by buddh4** [comment]
Works great, thanks!

**Comment by marijnh** [comment]
Great, published as 1.4.5
