### ISSUE TITLE
Click to view line markdown source

### ISSUE THREAD

**Issue by linonetwo** [ProseMirror/prosemirror-markdown#49]
Like https://laobubu.net/HyperMD/#README.md

Can this be achieved in prosemirror?

**Comment by marijnh** [comment]
It'd be awkward, since the extra markup characters aren't part of the document and you'd need serious scripted magic to make editing them feel like regular text editing.

Please use the [forum](https://discuss.prosemirror.net/), not the bug tracker, for questions in the future.
