### ISSUE TITLE
Whitespace at the start of paragraphs is stripped out by the parser

### ISSUE THREAD

**Issue by zanemcca** [ProseMirror/prosemirror-markdown#50]
I noticed that whitespace is stripped out sometimes by the parser which is causing inconsistencies in our collaborative editor sessions.

I pulled down the latest version of prosemirror-markdown to my machine and added a unit test to showcase the issue.

https://github.com/ProseMirror/prosemirror-markdown/compare/master...sunsama:test/precedding-whitespace

I am not sure if there is some legacy markdown reasons for this or if this is a legit bug. Any guidance would be highly appreciated.

**Comment by marijnh** [comment]
That's how markdown parsing is supposed to work—try for example [the official demo](https://spec.commonmark.org/dingus/), if you input `   foo` (three spaces and a word), you get `<p>foo</p>` out. Could you say a bit more about how this causes inconsistencies in your collab setup?

**Comment by zanemcca** [comment]
Thanks for the clarification @marijnh.

I have based our solution on https://github.com/outline/rich-markdown-editor which uses markdown as the source of truth for the document. So what effectively happens is preceding whitespace will work during a live editor session but the checksum/document verification will fail when we start a new session.

In the worst case scenario we have a live session and a new user joins in and attempts to initialize their editor. If we do not verify the state of the document with checksums and let it go ahead then all of the positions of changes that happen after the preceding whitespace will be off by a few places. These offsets generally result in the editor crashing because of out of range changes being applied. These out of range errors and their related cousins is what encouraged us to add in checksums for document verification.

I just hacked together a test to see if HTML as the source of truth would work better and when using the `preserveWhitespace: 'full'` option on the parser I can successfully render the exact same doc.

Do you think there might be an easy way to add the same option to the prosemirror-markdown parser?

**Comment by marijnh** [comment]
The markdown parser is a layer on top of the markdown-it parser library, so I don't think it's going to be easy to change the way it treats whitespace (and it wouldn't be clear how to do it anyway—whitespace at the start of a list item, or more than four spaces at the start of any block, is impossible to express in Markdown text).

So I think the direction you need to think in is having some document normalization step, possibly by just running the document through the markdown serializer and then parsing it again.

**Comment by zanemcca** [comment]
Thanks for the tip @marijnh! I ended up extending our fork of the rich-markdown-editor to accept HTML as it's input which lets us use the `{ preserveWhitespace: 'full' }` option. This made the most sense for us since our editor is not really strictly markdown.
