### ISSUE TITLE
bug in lists

### ISSUE THREAD

**Issue by williamstein** [ProseMirror/prosemirror-markdown#51]
In [the demo](https://prosemirror.net/examples/markdown/), clear the plain textbox and type:
```
* item
* another item
```
Then switch to WYSIWYM, then switch back, and you'll see
```
* item

* another item
```

This means something completely different in markdown -- it's a list with lots of space between each entry.

As far as I can tell, there isn't a way to even make a bulleted list without lots of space between entries using the WYSIWYM mode.

---

View the difference via Github's Markdown Renderer:

* item
* another item

VERSUS

* item

* another item

**Comment by williamstein** [comment]
The same issue occurs with enumerated lists.

**Comment by marijnh** [comment]
It seems that the markdown parser isn't setting the `tight` attribute (which stores the difference between the two types of Markdown lists), which is likely the source of this problem. I haven't checked how the current version of markdown-it exposes that, but I guess it shouldn't be too hard to fix that. Want to try creating a patch?

**Comment by williamstein** [comment]
> I haven't checked how the current version of markdown-it exposes that, [...]

I figured out how it does; markdown-it has a "hidden" attribute that the Prosemirror parser is ignoring.  See https://markdown-it.github.io/markdown-it/#Token.prototype.hidden for the docs about it.  In particular, 

> "If it's true, ignore this element when rendering. Used for tight lists to hide paragraphs."

Probably they used this approach as a sort of annoying hack to make their codebase easier to maintain...

> Want to try creating a patch?

Unsure.

**Comment by marijnh** [comment]
Attached patch seems to fix this.

**Comment by marijnh** [comment]
Probably in the link right above my comment. 

https://github.com/ProseMirror/prosemirror-markdown/commit/64f70279732344c4b5deef821c108fff3484bd66
