### ISSUE TITLE
Serializer does not escape '>' at start of line

### ISSUE THREAD

**Issue by roennibus** [ProseMirror/prosemirror-markdown#56]
#### Details
Markdown serializer currently does not escape a _greater-than_ character `>` occurring at start of line.

#### Version
prosemirror-markdown 1.5.1
Can be reproduced with [markdown example](https://prosemirror.net/examples/markdown/).

#### Steps to reprocude
1. Insert line starting with `>` in WYSIWYM mode.
2. Switch mode to markdown.
3. `>` character is not escaped.
4. Switch back to WYSIWYM.
5. Line is now unintentionally quoted.

![image](https://user-images.githubusercontent.com/90031491/131980347-f22ba51a-8dff-4bac-bbbc-a13e9c48bc37.png)
![image](https://user-images.githubusercontent.com/90031491/131980376-5725e6c0-6eac-473e-aa65-23b1b8adbc82.png)
![image](https://user-images.githubusercontent.com/90031491/131980447-55368162-ca4d-4134-95a4-447af2f176b3.png)

#### Expected result:
`>` character at start of line is escaped as `\>` during markdown serialization.

**Comment by marijnh** [comment]
Attached patch should help.
