### ISSUE TITLE
Escaping on serialization but not unescaping on parsing

### ISSUE THREAD

**Issue by hrobertson** [ProseMirror/prosemirror-markdown#58]
`defaultMarkdownSerializer` escapes text, however there is no mention of unescaping in `from_markdown.js`.

If `defaultMarkdownSerializer` is given the input `[` for example, it outputs `\[`.
If this is later fed into `defaultMarkdownParser`, the output is `\[` when it should be `[`

Content is escaped but never unescaped resulting in documents accumulating more and more backslashes.
Surely this is not correct default behaviour?

**Comment by marijnh** [comment]
Unescaping should be done by the [Markdown parser](https://markdown-it.github.io/), which seems to do it properly for `\[` at least in simple cases. Also, trying [the ProseMirror markdown example](https://prosemirror.net/examples/markdown/), I'm not seeing the problem you are describing. Can you provide a specific example of a document where this fails?

**Comment by IntranetFactory** [comment]
I tried the example, I appended `![logo](/logos/stock image.png)`

![image](https://user-images.githubusercontent.com/7462342/145793745-b10a98dd-3136-4a85-be0c-ac405e371cb8.png)

switched to WYSIWYM

![image](https://user-images.githubusercontent.com/7462342/145794017-9dc96a5c-17f1-4e1b-a501-fb2045a76dbc.png)

and switched back to markdown

![image](https://user-images.githubusercontent.com/7462342/145794244-e4154696-d48b-4ad0-b401-8e24cb228eea.png)

result: `![logo](/logos/stock image.png)` became `!\[logo\](/logos/stock image.png)`

**Comment by marijnh** [comment]
Ah, I see, the backslashes appear in the Markdown code, not the actual rendered text. That is intentional—the escaping will simply escape characters that _might_ have a meaning in Markdown, even if the way they appear in the text doesn't trigger that meaning.

**Comment by hrobertson** [comment]
I will try to find time to create a minimal repro.
