### ISSUE TITLE
Escaping underscore breaks link URLs that contain this character

### ISSUE THREAD

**Issue by enriquecastl** [ProseMirror/prosemirror-markdown#61]
### Version 

1.6.1

### What is the problem?

When serializing a document, Prosemirror-markdown breaks links with URLs that  that contain underscore characters. The change was introduced in: https://github.com/ProseMirror/prosemirror-markdown/commit/99155977dbfd010d4db5d0d50fe90b08942f01ba

### How to reproduce

The following sandbox contains a reproducible script: https://codesandbox.io/s/broken-links-prosemirror-markdown-r9ez0

**Comment by marijnh** [comment]
Attached patch should fix this.

**Comment by enriquecastl** [comment]
Thanks for the quick fix @marijnh 🙇🏼
