### ISSUE TITLE
Escaping special markdown characters causes problems with links

### ISSUE THREAD

**Issue by mstijak** [ProseMirror/prosemirror-markdown#65]
Users are occasionally pasting links directly in the editor. 

During serialization, the underscore character is escaped into `\_`. This causes problems later on when markdown is converted to HTML.

For example, `https://miro.com/app/board/abc_def` 

becomes 

`https://miro.com/app/board/abc\_def` 

which later becomes an unusable link:

`<a href="https://miro.com/app/board/abc\_def">https://miro.com/app/board/abc\_def</a>` .

What would be the best way to handle this issue? Should links be detected before escaping text or maybe there is some other way?

**Comment by mstijak** [comment]
Looking for underscore characters between letters would help greatly and that should be a simple fix.
But the problem would remain if an underscore appears at the end.
A safer way might be to look back for `(https?|ftp|mailto)://`, but this approach would be slower.

**Comment by duhaime** [comment]
@marijnh could you say a little about why underscores are escaped? We just bumped into the same issue...

**Comment by marijnh** [comment]
> could you say a little about why underscores are escaped?

Same reason all the other characters are escaped -- because they have a meaning in markdown.

**Comment by rj-david** [comment]
Seems like this is happening again with markdown-it 13.x

**Comment by rj-david** [comment]
@marijnh here are the URLs that recently caused an issue for us in production

https://www.youtube.com/watch?v=_wfHcgwejng
https://assets.onepropertee.com/344x0/forum-attachments/lead-boost---lead-matching-guidelines_-what-to-do-after-purchase_.L5EPjkWMaYHLLNt3X.jpg

For both cases, the latest version of ProseMirror-Markdown (using Markdown-it 13.x) resulted in escaped underscores. Previous versions before 1.9.x does not have the problem

**Comment by marijnh** [comment]
Markdown-it is not involved in Markdown serialization at all (only in parsing), so I don't think this related to the Markdown-it version. Version 1.6.1 introduces escaping of underscores, which is probably where this "broke" for you. But as far as I'm concerned, the current behavior is appropriate—underscores such as those in that URL _do_ have a meaning in Markdown, and should be escaped when serializing.

**Comment by rj-david** [comment]
It is unfortunate that there is a conflict between the URL spec and Markdown spec. Will try to handle this on the output instead

**Comment by rj-david** [comment]
I think we have to fork and repurpose the original solution of @mstijak since it is very common that URLs have underscore instead of users trying to emphasize part of the URL

https://github.com/ProseMirror/prosemirror-markdown/pull/66/files
