### ISSUE TITLE
Escape of dots in list items

### ISSUE THREAD

**Issue by susnux** [ProseMirror/prosemirror-markdown#75]
When there are dots, following a number, as text in list items they must be escaped.
Found by an user of the nextcloud text app: https://github.com/nextcloud/text/issues/2480 

---
E.g. consider this text:

Hello
* 1\. world
* 2\. world
* 3\. world

which is based on this source code:
```markdown
Hello
* 1\. world
* 2\. world
* 3\. world
```

But using the WYSIWYG editor it emits this markdown:
```markdown
Hello
* 1. world
* 2. world
* 3. world
```

which results in:

Hello
* 1. world
* 2. world
* 3. world

See also this example:
![Example within the WYSIWYG editor](https://user-images.githubusercontent.com/1855448/177165193-52d90780-c3d0-4b39-b16a-ba783ef27db3.gif)

**Comment by marijnh** [comment]
Attached patch should help.
