### ISSUE TITLE
Unnecessary escaping of plus sign?

### ISSUE THREAD

**Issue by eloquence** [ProseMirror/prosemirror-markdown#8]
The serializer currently escapes all plus signs, not just at the beginning of a line. Is this intentional, or an oversight? I can find no evidence in the spec that a plus sign is meaningful except as a bullet point list indicator. Other bullet point symbols (`*`,`-`) are already treated differently. Relevant lines:

https://github.com/eloquence/prosemirror-markdown/blob/master/src/to_markdown.js#L299-L300

**Comment by marijnh** [comment]
I think this is an oversight -- I don't believe plus has any other special meaning in Markdown.
