### ISSUE TITLE
Hard line breaks always also add newline

### ISSUE THREAD

**Issue by susnux** [ProseMirror/prosemirror-markdown#80]
I noticed that hard line breaks always add  a newline character, which breaks stuff when set `preserveWhitespaces: 'full'´ for paragraphs.

Consider this:
```markdown
*foo\
bar*
```

will result in
```html
<p><em>foo<br \>
bar</em></p>
```

And then serialized as:
```markdown
*foo \

 bar*
```

which results in this:
```html
<p>*foo \</p>
<p>bar*</p>
```

---
My use case:\
keep differences of markdown files after editing as small as possible, especially custom formatting (from external editors). E.g.:
```markdown
foo
bar
```

without `preserveWhitespaces: 'full'` this would result in
```markdown
foo bar
```

The rendered version would look the same, but the source file is different and may be harder to read.

**Comment by marijnh** [comment]
I don't quite understand the problem here. If I add a test for the document you show (in attached patch), that content seems to round-trip just fine, without any extra newlines being inserted.

**Comment by marijnh** [comment]
> It does not happen when using the provided markdown parser, but if happens if you set the parse options / parse rules of paragraphs to preserveWhitespace: true.

That's a DOM parser option, though. How does that effect Markdown deserializing?

**Comment by susnux** [comment]
As I said I do not use the provided parser, but plain `markdown-it` as the project uses quite a lot markdown extensions.

So this is only a problem if you use the `to_markdown` part of this nice project together with custom markdown parsing.
(I can understand if you decide that this is a *won't fix*)

**Comment by marijnh** [comment]
Ah, all right. I think this is something you'll have to address in your custom parser then.
