### ISSUE TITLE
Support passing in markdown-it `env`

### ISSUE THREAD

**Issue by segevfiner** [ProseMirror/prosemirror-markdown#86]
`markdown-it` can receive an `env` object in its parse call that can be used to retrieve and pass in some information into the parser for some plugins and token types. It would be nice to be able to pass it in.

**Comment by marijnh** [comment]
What kind of thing is this used for? Would you want to pass it in to the `parse` method, or the `MarkdownParser` constructor?

**Comment by segevfiner** [comment]
To the parse method.

See https://markdown-it.github.io/markdown-it/#MarkdownIt.parse & https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#data-flow

**Comment by marijnh** [comment]
I know what that argument is, what I was asking is what you are using it for.

**Comment by segevfiner** [comment]
To pass and receive environmental data from some custom markdown-it plugin.

**Comment by marijnh** [comment]
Added in attached patch.
