### ISSUE TITLE
Handling of `softbreak` is weird

### ISSUE THREAD

**Issue by segevfiner** [ProseMirror/prosemirror-markdown#91]
Currently `prosemirror-markdown` converts a `softbreak` to a `\n` in the `text` node, this seems to render as a line break when initially viewed, but is stripped away on the first edit of that text node. I think this is weird and unintuitive. How should this be handled better?

![Recording 2023-04-03 at 21 39 05](https://user-images.githubusercontent.com/24731903/229597898-b8ca7174-5efd-46e2-9c7c-567b064f5efb.gif)

**Comment by marijnh** [comment]
We could just convert them to spaces? Soft breaks don't really do anything more than spaces in default CommonMark, do they?

**Comment by marijnh** [comment]
I don't think it's reasonable to try to preserve them in the ProseMirror document. You can configure your markdown parser to convert them to hard breaks if you want, but converting them to a space seems reasonable default behavior. Does that sound workable?

**Comment by segevfiner** [comment]
I guess so. But I think it needs to be done by overriding the softbreak rule of `prosemirror-markdown`.

P.S. It would be interesting to have the ability to rewrap the Markdown text on output to some line width using soft breaks. I wonder if this can be done.
