### ISSUE TITLE
Add support for passing an extra env dictionary to the `MarkdownSerializer`

### ISSUE THREAD

**Issue by segevfiner** [ProseMirror/prosemirror-markdown#98]
This is useful for serialization rules that need additional data or configuration that isn't part of the document.

**Comment by marijnh** [comment]
Why not just have your serializer functions close over the data they need?

**Comment by segevfiner** [comment]
I don't want to create a new instance of MarkdownSerializer for each parse
cycle.

בתאריך יום ד׳, 17 במאי 2023, 10:58, מאת Marijn Haverbeke ‏<
***@***.***>:

**Comment by segevfiner** [comment]
I only need to create the env object and pass it to `serialize`, reusing the same global `MarkdownSerializer`.

**Comment by marijnh** [comment]
Ah, I see, it's an argument to `serialize`. Still, this seems to address a highly specific use case that's easily enough worked around by putting the values you need to access in some shared variable, so I don't think this needs to be in the library.
